---
#
# Local Kubernetes cluster without Traefik, since I want to configure it myself, especially for exposing the RTMP port.
# src: https://k3d.io/v5.6.3/usage/configfile/
#

apiVersion: k3d.io/v1alpha5
kind: Simple
servers: 1
agents: 0
image: docker.io/rancher/k3s:v1.30.1-k3s1
# ingress
ports:
  - port: 80:80
    nodeFilters:
      - server:0
  - port: 1935:1935
    nodeFilters:
      - server:0
# will use host docker registry
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:0

