services:
  db:
    image: postgres:13-alpine
    container_name: my-db
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: psql postgres --command "SELECT 1" -U postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - 5432:5432
