global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'localhost-spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9121']
        labels:
          Application: spring-boot-app
          Environment: localhost
          name: localhost-spring-boot-app-01
  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'localhost:8081' ]
        labels:
          application: cadvisor
          Application: spring-boot-app
          Environment: localhost
          name: localhost-spring-boot-app-01
